### PR TITLE
Allow data parameter to be any type.

### PR DESCRIPTION
**Pull request by unscriptable**
This threw me for a loop.  The error message ("Cannot read property 'isJoi' of null") made me think the error originated in joi code. :)  

The tests are awfully redundant.  Might be time to consolidate them?

### CODE REVIEW

**Comment by joegoldbeck** [comment]
Also, yeah DRYing up tests seems super reasonable. It's never been quite clear to me why they were done totally separately like that.

**Comment by unscriptable** [comment]
> What was the previous behavior? Data only as object?

Yes, which fails in the following use case:

```js
      // imagine workflowId is undefined due to another error
      const workflow = yield this._service.get(workflowId); 
      if (!workflow) {
        throw new NotFoundError(null, workflowId);
      }
```

I have since decided to include more information, not just `workflowId`, but I was not expecting any constraints on the `data` parameter.  

If you'd like me to only allow undefined, null, or object, I would be happy to remove some of the tests, tighten up the code, and add some documentation the the README.

Also, would you like me to increment the patch version?

**Comment by joegoldbeck** [comment]
I think we should allow all of them, but if we get a truthy non-object, it should convert that into an object (with some reasonable key). Thus we'd get permissive input behavior (which I think is probably critical for an error object) but consistent results.

I actually think this is a `minor` version bump, effectively extending the API.

**Comment by unscriptable** [comment]
Imho, transforming the `data` parameter from a non-object to an object `data` property is unexpected.  I would expect that we either disallow non-objects or allow them.

**Comment by unscriptable** [comment]
Ok, now that I unified the tests via a loop, I want to generate the classes in a loop, too.  They're all exactly the same. 🤓

**Comment by joegoldbeck** [comment]
Ok, let's just allow non-objects then. Perhaps objects can remain the preferred way in the documentation though, but we can allow all inputs to be safe.

**Comment by joegoldbeck** [comment]
The reasoning is that

`throw new NotFoundError(null, workflowId);` would likely be much more interpretable later as `throw new NotFoundError(null, { workflowId });`

**Comment by joegoldbeck** [comment]
What I'd really like to do is to log a `warn` anytime a non-object is passed, but since our logging is in the same layer, I think that's a non-option. I wonder if there's an easy way to bump our logging up to the environment layer. https://12factor.net/logs

**Comment by joegoldbeck** [comment]
Ignore a lot of my comments above now that we resolved the confusion. Lgtm!

**Pull request merged**
